import tokens, { serializeTokens } from './tokens'

import { PoolCategory } from './types'
import { SpecialPoolConfigType } from '../../state/types'

const serializedTokens = serializeTokens()
export const SpecialPoolsConfig: SpecialPoolConfigType[] = [
  {
    name: 'DeFiFarms 30K',
    link: 'round-1',
    description: "APR 700% | Lock-up tern 10 days",
    capGoal: 30000,
    childrenPools: [
      {
        sousId: 500,
        stakingToken: serializedTokens.defiynew,
        earningToken: serializedTokens.defiynew,
        contractAddress: {
          97: '0x4C15c57071EBCC4318F1C427878491d51262A854',
          56: '',
        },
        poolCategory: PoolCategory.CORE,
        harvest: true,
        sortOrder: 999,
        tokenPerBlock: '0.0578',
      },
      {
        sousId: 501,
        stakingToken: serializedTokens.usdt,
        earningToken: serializedTokens.defiynew,
        contractAddress: {
          97: '0xf1C20692a886cD9f8fD77eD6b779b482102f3916',
          56: '',
        },
        poolCategory: PoolCategory.CORE,
        harvest: true,
        sortOrder: 999,
        tokenPerBlock: '0.0578',
      },
      {
        sousId: 502,
        stakingToken: serializedTokens.wbnb,
        earningToken: serializedTokens.defiynew,
        contractAddress: {
          97: '0x4362013C43Ee076aC73bf1CF14533B1b52695f96',
          56: '',
        },
        poolCategory: PoolCategory.CORE,
        harvest: true,
        sortOrder: 999,
        tokenPerBlock: '0.0578',
      },
      {
        sousId: 503,
        stakingToken: serializedTokens.btcb,
        earningToken: serializedTokens.defiynew,
        contractAddress: {
          97: '0x6f2744f028e111fdDDd5F01d78C00F7b8FEF44D4',
          56: '',
        },
        poolCategory: PoolCategory.CORE,
        harvest: true,
        sortOrder: 999,
        tokenPerBlock: '0.0578',
      },
      {
        sousId: 504,
        stakingToken: serializedTokens.eth,
        earningToken: serializedTokens.defiynew,
        contractAddress: {
          97: '0x6c134C5D35EE70A7617E71B7a2707ebe71EB3096',
          56: '',
        },
        poolCategory: PoolCategory.CORE,
        harvest: true,
        sortOrder: 999,
        tokenPerBlock: '0.0578',
      },
      {
        sousId: 505,
        stakingToken: serializedTokens.cake,
        earningToken: serializedTokens.defiynew,
        contractAddress: {
          97: '0xc7109B8499ea12643aF743684Cdc299cEaa2e162',
          56: '',
        },
        poolCategory: PoolCategory.CORE,
        harvest: true,
        sortOrder: 999,
        tokenPerBlock: '0.0578',
      },
      // {
      //   sousId: 3,
      //   apr: 100,
      //   stakingToken: tokens.busd,
      //   earningToken: tokens.defiy,
      //   contractAddress: {
      //     97: '0xc7437617f89A23FA7eACB90f6b3D663055B5d467',
      //     56: '',
      //   },
      //   poolCategory: PoolCategory.CORE,
      //   depositFeeBP: '0',
      //   harvestInterval: '14400',
      //   tokenPerBlock: '0.01',
      //   sortOrder: 1,
      //   isFinished: false,
      // },
      // {
      //   sousId: 3,
      //   apr: 100,
      //   stakingToken: tokens.wbnb,
      //   earningToken: tokens.defiy,
      //   contractAddress: {
      //     97: '0xc7437617f89A23FA7eACB90f6b3D663055B5d467',
      //     56: '',
      //   },
      //   poolCategory: PoolCategory.CORE,
      //   depositFeeBP: '0',
      //   harvestInterval: '14400',
      //   tokenPerBlock: '0.01',
      //   sortOrder: 1,
      //   isFinished: false,
      // },
      // {
      //   sousId: 3,
      //   apr: 100,
      //   stakingToken: tokens.btcb,
      //   earningToken: tokens.defiy,
      //   contractAddress: {
      //     97: '0xc7437617f89A23FA7eACB90f6b3D663055B5d467',
      //     56: '',
      //   },
      //   poolCategory: PoolCategory.CORE,
      //   depositFeeBP: '0',
      //   harvestInterval: '14400',
      //   tokenPerBlock: '0.01',
      //   sortOrder: 1,
      //   isFinished: false,
      // },
      // {
      //   sousId: 3,
      //   apr: 100,
      //   stakingToken: tokens.eth,
      //   earningToken: tokens.defiy,
      //   contractAddress: {
      //     97: '0xc7437617f89A23FA7eACB90f6b3D663055B5d467',
      //     56: '',
      //   },
      //   poolCategory: PoolCategory.CORE,
      //   depositFeeBP: '0',
      //   harvestInterval: '14400',
      //   tokenPerBlock: '0.01',
      //   sortOrder: 1,
      //   isFinished: false,
      // },
      // {
      //   sousId: 3,
      //   apr: 100,
      //   stakingToken: tokens.cake,
      //   earningToken: tokens.defiy,
      //   contractAddress: {
      //     97: '0xc7437617f89A23FA7eACB90f6b3D663055B5d467',
      //     56: '',
      //   },
      //   poolCategory: PoolCategory.CORE,
      //   depositFeeBP: '0',
      //   harvestInterval: '14400',
      //   tokenPerBlock: '0.01',
      //   sortOrder: 1,
      //   isFinished: false,
      // },
    ],
  },
  {
    name: 'DeFiFarms 50K',
    link: 'round-2',
    description: "APR 700% | Lock-up tern 10 days",
    capGoal: 50000,
    childrenPools: [
      {
        sousId: 3,
        stakingToken: tokens.busd,
        earningToken: tokens.defiy,
        contractAddress: {
          97: '0xc7437617f89A23FA7eACB90f6b3D663055B5d467',
          56: '',
        },
        poolCategory: PoolCategory.CORE,
        depositFeeBP: '0',
        harvestInterval: '14400',
        tokenPerBlock: '0.01',
        sortOrder: 1,
        isFinished: false,
      },
    ],
  },
  {
    name: 'DeFiFarms 100K',
    link: 'round-3',
    description: "APR 700% | Lock-up tern 10 days",
    capGoal: 100000,
    childrenPools: [
      {
        sousId: 3,
        stakingToken: tokens.busd,
        earningToken: tokens.defiy,
        contractAddress: {
          97: '0xc7437617f89A23FA7eACB90f6b3D663055B5d467',
          56: '',
        },
        poolCategory: PoolCategory.CORE,
        depositFeeBP: '0',
        harvestInterval: '14400',
        tokenPerBlock: '0.01',
        sortOrder: 1,
        isFinished: false,
      },
    ],
  },
  {
    name: 'DeFiFarms 500K',
    link: 'round-4',
    description: "APR 700% | Lock-up tern 10 days",
    capGoal: 500000,
    childrenPools: [
      {
        sousId: 3,
        stakingToken: tokens.busd,
        earningToken: tokens.defiy,
        contractAddress: {
          97: '0xc7437617f89A23FA7eACB90f6b3D663055B5d467',
          56: '',
        },
        poolCategory: PoolCategory.CORE,
        depositFeeBP: '0',
        harvestInterval: '14400',
        tokenPerBlock: '0.01',
        sortOrder: 1,
        isFinished: false,
      },
    ],
  },
  {
    name: 'DeFiFarms 1500K',
    capGoal: 150000,
    link: 'round-5',
    description: "APR 700% | Lock-up tern 10 days",
    childrenPools: [
      {
        sousId: 3,
        stakingToken: tokens.busd,
        earningToken: tokens.defiy,
        contractAddress: {
          97: '0xc7437617f89A23FA7eACB90f6b3D663055B5d467',
          56: '',
        },
        poolCategory: PoolCategory.CORE,
        depositFeeBP: '0',
        harvestInterval: '14400',
        tokenPerBlock: '0.01',
        sortOrder: 1,
        isFinished: false,
      },
    ],
  },
]
